# Generated by Django 5.2.3 on 2025-06-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_interests_customuser_pedagogic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pedagogic_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('university', 'University'), ('adult', 'Adult Education'), ('general', 'General / All Levels')], default='general', help_text="User's current pedagogic level for tailored recommendations.", max_length=20, verbose_name='Pedagogic Level'),
            preserve_default=False,
        ),
    ]
