# Generated by Django 5.2.3 on 2025-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order',), 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='filecontent',
            options={'verbose_name': 'File Content', 'verbose_name_plural': 'File Contents'},
        ),
        migrations.AlterModelOptions(
            name='imagecontent',
            options={'verbose_name': 'Image Content', 'verbose_name_plural': 'Image Contents'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'verbose_name': 'Text Content', 'verbose_name_plural': 'Text Contents'},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': 'Video Content', 'verbose_name_plural': 'Video Contents'},
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='textcontent',
            name='text',
            field=models.TextField(default='', verbose_name='Text Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontent',
            name='url',
            field=models.URLField(default='', help_text='Paste YouTube, Vimeo, or direct video URL.', verbose_name='Video URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='file',
            field=models.FileField(upload_to='course_files/', verbose_name='File Attachment'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.ImageField(upload_to='course_images/', verbose_name='Image File'),
        ),
    ]
