# Generated by Django 5.2.3 on 2025-06-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pedagogic_level',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('university', 'University'), ('adult', 'Adult Education'), ('general', 'General / All Levels')], default='general', help_text='Target pedagogic level for this course.', max_length=20),
        ),
    ]
